
name: Check For Changes to Monitored Files

on:
  push:
    branches:
      - main

jobs:
  check_changes_and_alert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

    - name: Check and Alert if watched files changed
      id: check-and-alert
      run: |
        # Define the list of filenames to watch for changes
        watched_files=("config.json")
        if [[ ${{ github.event_name }} == 'pull_request' ]]; then
          changed_files=$(git diff --name-only -r HEAD^1 HEAD)
        else
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
        fi
        for file in $changed_files; do
          for watched_file in "${watched_files[@]}"; do
            if [[ $file == *"$watched_file"* ]]; then
              failure()
            fi
          done
        done
